Better type-checking errors (#662)
Instead of printing errors on every failure, accumulate errors for each
operation. If any fails, then print a message. It changes errors such
as:

```
error: type mismatch in i64.store, expected i32 but got f32.
error: type mismatch in i64.store, expected i64 but got i32.
```

to:

```
error: type mismatch in i64.store, expected [i32, i64] but got [f32, i32]
```